name: Auto Merge PR
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check if PR can be merged
        id: check_mergeable
        run: |
          # 检查 PR 是否可合并（无冲突）
          mergeable=$(gh pr view ${{ github.event.pull_request.number }} --json mergeable -q .mergeable)
          echo "mergeable=$mergeable" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if PR only contains additions
        id: check_additions_only
        if: steps.check_mergeable.outputs.mergeable == 'true'
        run: |
          # 检查 PR 是否只包含新增内容
          files=$(gh pr view ${{ github.event.pull_request.number }} --json files -q '.files[]')
          additions_only=true
          
          for file in $files; do
            changes=$(gh pr view ${{ github.event.pull_request.number }} --json files -q ".files[] | select(.path == \"$file\") | {additions, deletions, changes}")
            deletions=$(echo $changes | jq .deletions)
            
            if [ "$deletions" -gt 0 ]; then
              additions_only=false
              break
            fi
          done
          
          echo "additions_only=$additions_only" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Auto merge PR
        if: steps.check_mergeable.outputs.mergeable == 'true' && steps.check_additions_only.outputs.additions_only == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}