name: Auto Merge PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 获取最近两次提交用于 diff

      - name: Check for merge conflicts
        run: |
          git fetch origin ${{ github.base_ref }}
          if ! git merge-base --is-ancestor origin/${{ github.base_ref }} HEAD; then
            echo "Merge conflict detected, exiting."
            exit 1
          fi

      - name: Check if only new content was added
        run: |
          CHANGED_FILES=$(git diff --name-status HEAD^ | awk '{print $1}')
          if echo "$CHANGED_FILES" | grep -qE '^(M|D)'; then
            echo "PR contains modified or deleted files, not merging."
            exit 1
          fi

      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
